#!/bin/sh

sed -i 's/-DKDE4_BUILD_TESTS=false/-DKDE4_BUILD_TESTS=true/' debian/rules
if [ -d /usr/lib/ccache ]; then
    export PATH="/usr/lib/ccache:$PATH"
fi
debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules build 2>&1

if [ -z "$HOME" ] || [ ! -d "$HOME" ]; then
    [ -e debian/tests.home ] || mkdir debian/tests.home
    export HOME="$(pwd)/debian/tests.home"
    trap "rm -rf debian/tests.home" EXIT
fi
mkdir -p "$HOME"/.config || true
mkdir -p "$HOME"/.kde-unit-test || true
xvfb-run -a --server-args="-screen 0 1024x768x24" \
    dbus-launch --exit-with-session debian/tests/testsuite.xsession
